# Generated by Django 4.2.1 on 2023-05-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('temp', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('feels_like', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('visibility', models.FloatField()),
            ],
        ),
    ]
